import type { SearchSongResult } from './types';

export const catalog: SearchSongResult[] = [
  {
    songTitle: 'Titanium',
    artistName: 'David Guetta feat. Sia',
    albumName: 'Nothing but the Beat',
    appleMusicId: 'catalog-titanium',
    artworkUrl: 'https://placehold.co/400x400/0b1225/7cf7d4?text=Titanium',
    durationMs: 245000,
    bpm: 126,
    genre: 'Dance',
    style: 'EDM',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Levitating',
    artistName: 'Dua Lipa',
    albumName: 'Future Nostalgia',
    appleMusicId: 'catalog-levitating',
    artworkUrl: 'https://placehold.co/400x400/111827/7f9cff?text=Levitating',
    durationMs: 203000,
    bpm: 103,
    genre: 'Pop',
    style: 'Nu-disco',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'One More Time',
    artistName: 'Daft Punk',
    albumName: 'Discovery',
    appleMusicId: 'catalog-onemoretime',
    artworkUrl: 'https://placehold.co/400x400/090b13/55e6a5?text=Daft+Punk',
    durationMs: 320000,
    bpm: 123,
    genre: 'Electronic',
    style: 'House',
    energyLevel: 'peak',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Crazy in Love',
    artistName: 'Beyonc\u00e9 feat. Jay-Z',
    albumName: 'Dangerously in Love',
    appleMusicId: 'catalog-crazyinlove',
    artworkUrl: 'https://placehold.co/400x400/251218/ff6b8b?text=Crazy+in+Love',
    durationMs: 236000,
    bpm: 99,
    genre: 'R&B',
    style: 'Party',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Yeah!',
    artistName: 'Usher feat. Lil Jon & Ludacris',
    albumName: 'Confessions',
    appleMusicId: 'catalog-yeah',
    artworkUrl: 'https://placehold.co/400x400/20120f/ffd36a?text=Yeah',
    durationMs: 250000,
    bpm: 105,
    genre: 'Hip-Hop',
    style: 'Club',
    energyLevel: 'peak',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Can\'t Stop the Feeling!',
    artistName: 'Justin Timberlake',
    albumName: 'Trolls',
    appleMusicId: 'catalog-cantstop',
    artworkUrl: 'https://placehold.co/400x400/10161f/b7ffe9?text=Feeling',
    durationMs: 236000,
    bpm: 113,
    genre: 'Pop',
    style: 'Feel-good',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Turn Down for What',
    artistName: 'DJ Snake & Lil Jon',
    albumName: 'Turn Down for What',
    appleMusicId: 'catalog-tdfw',
    artworkUrl: 'https://placehold.co/400x400/0f172a/ff9aa8?text=Turn+Down',
    durationMs: 213000,
    bpm: 100,
    genre: 'EDM',
    style: 'Drop',
    energyLevel: 'peak',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Blinding Lights',
    artistName: 'The Weeknd',
    albumName: 'After Hours',
    appleMusicId: 'catalog-blindinglights',
    artworkUrl: 'https://placehold.co/400x400/101729/7cf7d4?text=Lights',
    durationMs: 200000,
    bpm: 171,
    genre: 'Synth-pop',
    style: 'Retro',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'September',
    artistName: 'Earth, Wind & Fire',
    albumName: 'The Best of Earth, Wind & Fire',
    appleMusicId: 'catalog-september',
    artworkUrl: 'https://placehold.co/400x400/0f1424/7f9cff?text=September',
    durationMs: 213000,
    bpm: 126,
    genre: 'Funk',
    style: 'Disco',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Superstition',
    artistName: 'Stevie Wonder',
    albumName: 'Talking Book',
    appleMusicId: 'catalog-superstition',
    artworkUrl: 'https://placehold.co/400x400/23170f/f8d66d?text=Superstition',
    durationMs: 254000,
    bpm: 100,
    genre: 'Soul',
    style: 'Groove',
    energyLevel: 'medium',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Mo Bamba',
    artistName: 'Sheck Wes',
    albumName: 'Mudboy',
    appleMusicId: 'catalog-mobamba',
    artworkUrl: 'https://placehold.co/400x400/0d1020/ff6b8b?text=Mo+Bamba',
    durationMs: 196000,
    bpm: 146,
    genre: 'Hip-Hop',
    style: 'Hype',
    energyLevel: 'peak',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Murder on the Dancefloor',
    artistName: 'Sophie Ellis-Bextor',
    albumName: 'Read My Lips',
    appleMusicId: 'catalog-murder',
    artworkUrl: 'https://placehold.co/400x400/0b1320/b7ffe9?text=Dancefloor',
    durationMs: 232000,
    bpm: 117,
    genre: 'Pop',
    style: 'Dance',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Shivers',
    artistName: 'Ed Sheeran',
    albumName: '= (Equals)',
    appleMusicId: 'catalog-shivers',
    artworkUrl: 'https://placehold.co/400x400/111827/ffd36a?text=Shivers',
    durationMs: 207000,
    bpm: 141,
    genre: 'Pop',
    style: 'Upbeat',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  },
  {
    songTitle: 'Get Lucky',
    artistName: 'Daft Punk feat. Pharrell Williams',
    albumName: 'Random Access Memories',
    appleMusicId: 'catalog-getlucky',
    artworkUrl: 'https://placehold.co/400x400/10131e/55e6a5?text=Get+Lucky',
    durationMs: 369000,
    bpm: 116,
    genre: 'Funk',
    style: 'Disco-house',
    energyLevel: 'high',
    sourceProvider: 'catalog'
  }
];
